# Generated by Django 4.0.6 on 2022-08-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_solicitudpropietario_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpropietario',
            name='year',
            field=models.CharField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], max_length=4),
        ),
    ]
