# Generated by Django 4.0.6 on 2022-08-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_solicitudpropietario_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpropietario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('revision', 'Necesita mas informacion')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudpropietario',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default='2016'),
        ),
    ]
