# Generated by Django 4.0.6 on 2022-08-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0002_remove_vehicle_car_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='car_categorie',
            field=models.ManyToManyField(blank=True, to='carrental.carcategories'),
        ),
    ]
