# Generated by Django 4.0.6 on 2022-08-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0003_carcategories_vehicle_car_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='car_categorie',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='car_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrental.carcategories'),
        ),
    ]
