# Generated by Django 4.0.6 on 2022-08-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0004_remove_vehicle_car_categorie_vehicle_car_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
