# Generated by Django 4.0.6 on 2022-08-10 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0005_vehicle_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_amount', models.FloatField()),
                ('add_charges', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datafast',
                'verbose_name_plural': 'Datafast',
            },
        ),
    ]
