# Generated by Django 4.0.6 on 2022-08-10 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrental', '0006_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rental_start', models.DateTimeField()),
                ('rental_stop', models.DateTimeField()),
                ('reserva_status', models.CharField(choices=[('Confirmado', 'CONFIRMADO'), ('Reservado', 'RESERVA TEMPORAL'), ('Rechazado', 'RECHAZADO'), ('Cancelado', 'CANCELADO')], max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrental.pago')),
                ('rental_dropoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_dropoff', to='carrental.spots')),
                ('rental_pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_pickup', to='carrental.spots')),
                ('reserved_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrental.vehicle')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
