# Generated by Django 4.0.6 on 2022-08-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0008_reclamoconductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamoconductor',
            name='claim_status',
            field=models.CharField(choices=[('Reclamo Recibido', 'Reclamo Recibido'), ('Analizando Informacion', 'Analizando Informacion'), ('Pago Pendiente', 'Pago Pendiente'), ('Transferido a Cuenta', 'Transferido a Cuenta'), ('Rechazado', 'Rechazado')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='pago_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrental.pago'),
        ),
    ]
